export default [
  {
    type: 'user',
    category: 'event',
    name: 'host',
    min_value: 1,
  },
  {
    type: 'user',
    category: 'event',
    name: 'host',
    min_value: 10,
    difficulty: 1,
  },
  {
    type: 'user',
    category: 'event',
    name: 'host',
    min_value: 100,
    difficulty: 2,
  },
  {
    type: 'user',
    category: 'event',
    name: 'host',
    min_value: 1000,
    difficulty: 3,
  },

  {
    type: 'user',
    category: 'participation',
    name: 'user',
    min_value: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'user',
    min_value: 10,
    difficulty: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'user',
    min_value: 100,
    difficulty: 2,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'user',
    min_value: 1000,
    difficulty: 3,
  },

  {
    type: 'user',
    category: 'participation',
    name: 'guest',
    min_value: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'guest',
    min_value: 10,
    difficulty: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'guest',
    min_value: 100,
    difficulty: 2,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'guest',
    min_value: 1000,
    difficulty: 3,
  },

  {
    type: 'user',
    category: 'participation',
    name: 'mod',
    min_value: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'mod',
    min_value: 10,
    difficulty: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'mod',
    min_value: 100,
    difficulty: 2,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'mod',
    min_value: 1000,
    difficulty: 3,
  },

  {
    type: 'user',
    category: 'participation',
    name: 'vip',
    min_value: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'vip',
    min_value: 10,
    difficulty: 1,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'vip',
    min_value: 100,
    difficulty: 2,
  },
  {
    type: 'user',
    category: 'participation',
    name: 'vip',
    min_value: 1000,
    difficulty: 3,
  },

  // EVENT
  {
    type: 'event',
    category: 'participation',
    name: 'popularity',
    min_value: 10,
    difficulty: 1,
  },
  {
    type: 'event',
    category: 'participation',
    name: 'popularity',
    min_value: 100,
    difficulty: 2,
  },
  {
    type: 'event',
    category: 'participation',
    name: 'popularity',
    min_value: 1000,
    difficulty: 3,
  },

  {
    type: 'event',
    category: 'react',
    name: 'viral',
    min_value: 10,
    difficulty: 1,
  },
  {
    type: 'event',
    category: 'react',
    name: 'viral',
    min_value: 100,
    difficulty: 2,
  },
  {
    type: 'event',
    category: 'react',
    name: 'viral',
    min_value: 1000,
    difficulty: 3,
  },

  {
    type: 'event',
    category: 'event',
    name: 'host_first',
    difficulty: 3,
  },
  {
    type: 'event',
    category: 'event',
    name: 'participation_first',
    difficulty: 3,
  },
];
